<template>
  <div class="flex flex-col min-h-screen bg-gradient-to-br from-slate-100 to-blue-50">
    <!-- Header -->
    <header class="flex items-center gap-3 h-14 px-4 md:px-6 bg-white border-b border-slate-200 shadow-sm">
      <div class="flex items-center gap-2.5">
        <div class="w-7 h-7 bg-blue-700 rounded-md flex items-center justify-center flex-shrink-0">
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none" role="img" aria-label="Slotted angle rack icon">
            <rect x="2" y="1" width="2" height="14" fill="white" rx="0.5"/>
            <rect x="12" y="1" width="2" height="14" fill="white" rx="0.5"/>
            <rect x="2" y="5" width="12" height="1.5" fill="white" rx="0.5"/>
            <rect x="2" y="10" width="12" height="1.5" fill="white" rx="0.5"/>
          </svg>
        </div>
        <div>
          <div class="text-sm font-bold text-slate-800 leading-none">Rack Visualizer</div>
          <div class="text-xs text-slate-500 mt-0.5">Slotted Angle Rack Designer</div>
        </div>
      </div>
      <div class="hidden sm:block ml-auto text-xs text-slate-400">Drag shelves on canvas or use inputs · 1" snap increments</div>
    </header>

    <!-- Main -->
    <main class="flex flex-col lg:flex-row flex-1 min-h-0 gap-4 lg:gap-0 p-4 lg:p-0">
      <!-- Canvas Area -->
      <div class="flex-1 lg:overflow-y-auto lg:p-4 flex items-start justify-center order-1 lg:order-none min-h-0">
        <div class="w-full max-w-xl">
          <IsometricRack @canvasReady="onCanvasReady" />
        </div>
      </div>
      
      <!-- Sidebar / Control Panel -->
      <aside class="w-full lg:w-72 bg-white lg:border-l lg:border-slate-200 lg:overflow-y-auto lg:p-4 lg:shadow-md order-2 lg:order-none">
        <ControlPanel
          @exportJson="handleExportJson"
          @exportPng="handleExportPng"
          @exportPdf="handleExportPdf"
        />
      </aside>
    </main>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import IsometricRack from './components/IsometricRack.vue'
import ControlPanel from './components/ControlPanel.vue'
import { useRackStore, fmt } from './stores/rack'

const store = useRackStore()
const canvasEl = ref<HTMLCanvasElement | null>(null)

function onCanvasReady(el: HTMLCanvasElement | null) {
  canvasEl.value = el
}

function handleExportJson() {
  const config = {
    version: '1.0',
    exportedAt: new Date().toISOString(),
    dimensions: store.dimensions,
    plateCount: store.plateCount,
    plates: store.plates.map(p => ({ id: p.id, positionIn: p.positionIn, isManual: p.isManual })),
      config: {
        unit: store.unit,
        pillarThicknessIn: store.pillarThicknessIn,
        plateThicknessIn: store.plateThicknessIn,
        floorGapIn: store.floorGapIn,
        stepSizeIn: store.stepSizeIn,
        rotationDeg: store.rotationDeg,
      },
  }
  const blob = new Blob([JSON.stringify(config, null, 2)], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url; a.download = 'rack-config.json'; a.click()
  URL.revokeObjectURL(url)
}

function handleExportPng() {
  const canvas = canvasEl.value; if (!canvas) return
  const a = document.createElement('a')
  a.href = canvas.toDataURL('image/png'); a.download = 'rack-visualizer.png'; a.click()
}

function handleExportPdf() {
  const canvas = canvasEl.value; if (!canvas) return
  const imgData = canvas.toDataURL('image/png')
  const { widthIn: w, depthIn: d, heightIn: h } = store.dimensions
  const title = `${fmt(w, store.unit)} × ${fmt(d, store.unit)} × ${fmt(h, store.unit)}`
  const win = window.open('', '_blank'); if (!win) return
  win.document.write(`<!DOCTYPE html><html><head>
    <title>Rack — ${title}</title>
    <style>body{margin:0;padding:20px;font-family:Inter,sans-serif;background:#fff}
    h1{font-size:16px;color:#2d3748;margin:0 0 8px}p{font-size:12px;color:#718096;margin:0 0 16px}
    img{max-width:100%;border:1px solid #e2e8f0;border-radius:8px}@media print{body{padding:0}}</style>
  </head><body>
    <h1>Slotted Angle Rack — ${title} (W×D×H)</h1>
    <p>Generated by Rack Visualizer · ${new Date().toLocaleDateString()}</p>
    <img src="${imgData}" />
    <script>window.onload=()=>{window.print();window.close()}<\/script>
  </body></html>`)
  win.document.close()
}
</script>
