<template>
  <div class="app">
    <!-- Header -->
    <header class="app-header">
      <div class="logo">
        <div class="logo-icon">
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
            <rect x="2" y="1" width="2" height="14" fill="white" rx="0.5"/>
            <rect x="12" y="1" width="2" height="14" fill="white" rx="0.5"/>
            <rect x="2" y="5" width="12" height="1.5" fill="white" rx="0.5"/>
            <rect x="2" y="10" width="12" height="1.5" fill="white" rx="0.5"/>
          </svg>
        </div>
        <div>
          <div class="app-title">Rack Visualizer</div>
          <div class="app-subtitle">Slotted Angle Rack Designer</div>
        </div>
      </div>
      <div class="app-hint">Drag shelves on canvas or use inputs · 1" snap increments</div>
    </header>

    <!-- Main -->
    <main class="app-main">
      <div class="canvas-area">
        <IsometricRack @canvasReady="onCanvasReady" />
      </div>
      <aside class="sidebar">
        <ControlPanel
          @exportJson="handleExportJson"
          @exportPng="handleExportPng"
          @exportPdf="handleExportPdf"
        />
      </aside>
    </main>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import IsometricRack from './components/IsometricRack.vue'
import ControlPanel from './components/ControlPanel.vue'
import { useRackStore, fmt } from './stores/rack'

const store = useRackStore()
const canvasEl = ref<HTMLCanvasElement | null>(null)

function onCanvasReady(el: HTMLCanvasElement | null) {
  canvasEl.value = el
}

function handleExportJson() {
  const config = {
    version: '1.0',
    exportedAt: new Date().toISOString(),
    dimensions: store.dimensions,
    plateCount: store.plateCount,
    plates: store.plates.map(p => ({ id: p.id, positionIn: p.positionIn, isManual: p.isManual })),
    config: {
      unit: store.unit,
      pillarThicknessIn: store.pillarThicknessIn,
      plateThicknessIn: store.plateThicknessIn,
      floorGapIn: store.floorGapIn,
    },
  }
  const blob = new Blob([JSON.stringify(config, null, 2)], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url; a.download = 'rack-config.json'; a.click()
  URL.revokeObjectURL(url)
}

function handleExportPng() {
  const canvas = canvasEl.value; if (!canvas) return
  const a = document.createElement('a')
  a.href = canvas.toDataURL('image/png'); a.download = 'rack-visualizer.png'; a.click()
}

function handleExportPdf() {
  const canvas = canvasEl.value; if (!canvas) return
  const imgData = canvas.toDataURL('image/png')
  const { widthIn: w, depthIn: d, heightIn: h } = store.dimensions
  const title = `${fmt(w, store.unit)} × ${fmt(d, store.unit)} × ${fmt(h, store.unit)}`
  const win = window.open('', '_blank'); if (!win) return
  win.document.write(`<!DOCTYPE html><html><head>
    <title>Rack — ${title}</title>
    <style>body{margin:0;padding:20px;font-family:Inter,sans-serif;background:#fff}
    h1{font-size:16px;color:#2d3748;margin:0 0 8px}p{font-size:12px;color:#718096;margin:0 0 16px}
    img{max-width:100%;border:1px solid #e2e8f0;border-radius:8px}@media print{body{padding:0}}</style>
  </head><body>
    <h1>Slotted Angle Rack — ${title} (W×D×H)</h1>
    <p>Generated by Rack Visualizer · ${new Date().toLocaleDateString()}</p>
    <img src="${imgData}" />
    <script>window.onload=()=>{window.print();window.close()}<\/script>
  </body></html>`)
  win.document.close()
}
</script>

<style scoped>
.app { min-height:100vh; background:linear-gradient(135deg,#f1f5f9 0%,#eff6ff 100%); display:flex; flex-direction:column; }

.app-header {
  background:#fff; border-bottom:1px solid #e2e8f0; padding:12px 24px;
  display:flex; align-items:center; gap:12px; box-shadow:0 1px 3px rgba(0,0,0,0.06);
}
.logo { display:flex; align-items:center; gap:10px; }
.logo-icon { width:28px; height:28px; background:#1d4ed8; border-radius:6px; display:flex; align-items:center; justify-content:center; }
.app-title { font-size:15px; font-weight:700; color:#1e293b; line-height:1; }
.app-subtitle { font-size:11px; color:#64748b; margin-top:2px; }
.app-hint { margin-left:auto; font-size:12px; color:#94a3b8; }

.app-main { display:flex; flex:1; min-height:0; }
.canvas-area { flex:1; overflow:auto; padding:16px; display:flex; align-items:flex-start; justify-content:center; }
.canvas-area > * { width:100%; max-width:740px; }

.sidebar { width:288px; background:#fff; border-left:1px solid #e2e8f0; overflow-y:auto; padding:16px; box-shadow:-1px 0 4px rgba(0,0,0,0.04); flex-shrink:0; }
</style>
